cp -r ~/.config/i3 ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/i3status ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/i3block ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/i3block_scripts ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/alacritty ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/htop ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/rofi ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.config/betterlockscreen ~/git/setup/dotfiles/.config >> ~/log.log
cp -r ~/.zshrc ~/git/setup/dotfiles/homedir/.zshrc >> ~/log.log
cp -r ~/.tmux.conf ~/git/setup/dotfiles/homedir/.tmux.conf >> ~/log.log
cp -r ~/.vim/autoload ~/git/setup/dotfiles/homedir >> ~/log.log
cp -r ~/.vim/colors ~/git/setup/dotfiles/homedir >> ~/log.log
cp -r ~/.vimrc ~/git/setup/dotfiles/homedir/.vimrc >> ~/log.log
cp -r /etc/X11/xorg.conf.d/ ~/git/setup/dotfiles >> ~/log.log
cp -r /etc/modprobe.d/ ~/git/setup/ >> ~/log.log
