# Alacrittys default color scheme pre-0.13 (based on tomorrow_night)
# https://github.com/alacritty/alacritty/blob/v0.12.3/alacritty/src/config/color.rs

[colors.primary]
foreground = '#c5c8c6'
background = '#134427'

[colors.normal]
black = '#1d1f21'
red = '#cc6666'
green = '#b5bd68'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#8abeb7'
white = '#c5c8c6'

[colors.bright]
black = '#666666'
red = '#d54e53'
green = '#b9ca4a'
yellow = '#e7c547'
blue = '#7aa6da'
magenta = '#c397d8'
cyan = '#70c0b1'
white = '#eaeaea'

[colors.dim]
black = '#131415'
red = '#864343'
green = '#777c44'
yellow = '#9e824c'
blue = '#556a7d'
magenta = '#75617b'
cyan = '#5b7d78'
white = '#828482'
